### PR TITLE
Tendermint refactor

### PR DESCRIPTION
**Pull request by roignpar**
Various fixes, additions, optimizations and refactoring for the Tendermint integration.

### CODE REVIEW

**Review by pienkowb — APPROVED** [review]
LGTM, thanks for cleaning up the code 👍

**Review by sosedoff — APPROVED** [review]
LGTM. Do we plan on supplying any tests for this integration?

**Comment by roignpar** [comment]
@sosedoff the NEAR implementation only has some unit tests for triggers: https://github.com/graphprotocol/graph-node/blob/master/chain/near/src/trigger.rs#L143
what would we test if we did? only unit?

**Comment by pienkowb** [comment]
We have these two tasks for defining our testing strategy:

https://figmentio.atlassian.net/browse/GRAPH-37
https://figmentio.atlassian.net/browse/GRAPH-38

**Pull request merged**
