### PR TITLE
Pass transaction data to a message handler

### PR DESCRIPTION
**Pull request by pienkowb**
This PR covers [GRAPH-472](https://figmentio.atlassian.net/browse/GRAPH-472) and [GRAPH-463](https://figmentio.atlassian.net/browse/GRAPH-463).

Let's discuss the tradeoff between passing the whole `TxResult` structure vs. just individual fields (e.g. `ResponseDeliverTx.code`, `TxResult.index`).

### CODE REVIEW

**Comment by Seb-figment** [comment]
If we pass the whole TxResult this will also include the message and all others message in that Transaction. It kind of defeat the purpose of the messageHandler in my opinion. I think only the code and index is enough context for a message. If more is needed a subgraph developer should probably use the transactionHandler.

**Comment by pienkowb** [comment]
> If we pass the whole TxResult this will also include the message and all others message in that Transaction. It kind of defeat the purpose of the messageHandler in my opinion. I think only the code and index is enough context for a message. If more is needed a subgraph developer should probably use the transactionHandler.

I looked at the `TxResult` and `ResponseDeliverTx` structures and I see other fields that could be useful too - for instance, the transaction hash (`TxResult.hash`).

To me, it all comes down to what is the impact of passing the whole structure on the indexing performance. Before we introduced a light block, we passed the full block structure to every handler and the indexing speed was similar.

I think we have ways to actually measure this.

**Comment by Seb-figment** [comment]
If we are confident that the performance won't be affected then we can pass the whole `TxResult`. This way all future need will be covered.

**Comment by pienkowb** [comment]
I looked at Prometheus metrics and it turns out there's a ~3ms difference in the handler execution time, which makes a ~30% increase. That would have a significant impact on the indexing performance.

Screenshot 2022-09-02 at 15 00 10 (annotated)

I'll open a new PR with only selected transaction fields passed to the handler (instead of a full transaction object).

**Pull request closed without merging**
